### ISSUE TITLE
抓取数据不准确

### ISSUE THREAD

**Issue by hallowsman** [hello2mao/XLogging#3]
抓取的数据好多不准确

**Comment by hallowsman** [comment]
okhttp框架请求https协议为什么抓取不到呢？

**Comment by hello2mao** [comment]
@hallowsman 
因为Okhttp3对SSL做了特殊处理导致的，参见[https://github.com/square/okhttp/issues/184](https://github.com/square/okhttp/issues/184)。
Okhttp3相应的处理在http://androidxref.com/8.0.0_r4/xref/external/okhttp/android/main/java/com/squareup/okhttp/HttpsHandler.java 92行
